/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author GART
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSimulacionCarga
     */
    public VentanaInicio() {
        initComponents();
        
        //Cargar el icono de empresa
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Recursos/IconoEmpresa.png"));
        if(imgIcon != null) {
            this.setIconImage(imgIcon.getImage());
        }
        else {
            System.err.println("No se pudo cargar el icono desde la ruta especificada.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIcono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(660, 300));

        jLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelIcono, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelIcono;
    // End of variables declaration//GEN-END:variables

    
    public void getJLabelIcono(Icon icono){
        jLabelIcono.setIcon(icono);
    }
}